### ISSUE TITLE
ToDo: Azure IoT Hub Setup & Development, Web App

### ISSUE THREAD

**Issue by nikolxx** [spincraft/IoT-WINC1500#1]
- [ ] Setup an IoT Hub in Azure that can be used to push data to the cloud
- [ ] Get Hostname, ID, & Key to be used on Atmel guy
- [ ] Develop internal flow of IoT Hub --> Web app
- [ ] Make web app to display data that's coming through (data format TBD)
