### ISSUE TITLE
ToDo: Develop Testing Approach/Solution

### ISSUE THREAD

**Issue by nikolxx** [spincraft/IoT-WINC1500#13]
Goal: Make the example project easily testable.

- [ ] Identify what can be tested from the downlink
- [ ] Identify what can be tested from the uplink
- [ ] Develop a breakout board to interface with hardware
- [ ] Develop scripting to do the testing
- [ ] Integrate the test data to Azure
- [ ] Make an easy UI for the testing
