### ISSUE TITLE
ToDo: Security Model

### ISSUE THREAD

**Issue by nikolxx** [spincraft/IoT-WINC1500#2]
- [ ] Investigate Crypto chip (ATECC108) to understand capabilities
- [ ] Investigate uC (SAMD21) to understand capabilities. Ensure SAML21 has the same capabilities
- [ ] Define security architecture
- [ ] Define encryption algorithm
- [ ] Make security architecture diagram for documentation (Visio?)

Goal: To implement a security architecture for the device<-->Azure implementation.
