### ISSUE TITLE
ToDo: Licensing

### ISSUE THREAD

**Issue by nikolxx** [spincraft/IoT-WINC1500#3]
Goal: Define the licensing of this code/application.

- [ ] Define the limits on usage at a high level (if any)
- [ ] Define the license to use (MIT, CC-SA, BSD, Modified existing, etc)
- [ ] Define the header to include in each source file, including a reference to authors/support contact
