### ISSUE TITLE
ToDo: Code: Add timestamp

### ISSUE THREAD

**Issue by nikolxx** [spincraft/IoT-WINC1500#5]
- [ ] Add realtime clock driver, etc
- [ ] Get realtime clock working & test it
- [ ] Sync time with an online source
- [ ] Add a timestamp to the data
- [ ] Add timestamp to the Azure connection (since it's required)
