### ISSUE TITLE
ToDo: Code: Replace PubNub publishing with Azure

### ISSUE THREAD

**Issue by nikolxx** [spincraft/IoT-WINC1500#7]
Goal: To publish data to Azure instead of PubNub

- [ ] Establish a connection to Azure
- [ ] Figure out what data to pass
- [ ] Test passing a lot of data (stress testing)
