### ISSUE TITLE
ToDo: Code: Add Downlink Functionality

### ISSUE THREAD

**Issue by nikolxx** [spincraft/IoT-WINC1500#8]
Goal: Develop pushing down from Azure to device.

- [ ] Decide on what data to send back down
- [ ] Add code/drivers for functionality to physically respond to data (i.e. GPIO, PWM, etc)
- [ ] Develop receiver for data downlink
- [ ] Test downlink with lots of data (stress test)
