### ISSUE TITLE
ToDo: Code: Protocol Definition

### ISSUE THREAD

**Issue by nikolxx** [spincraft/IoT-WINC1500#9]
Goal: Define protocol for uplink and downlink.

- [ ] Define the data that will be passed up to the cloud.
- [ ] Define the data that will be passed down from the cloud.
- [ ] Define the uplink protocol (ASCII, binary, etc, and defined fields)
- [ ] Define the downlink protocol (ASCII, binary, etc, and defined fields)
- [ ] Consider encryption (see ToDo: Security Model)
